In [6]:
import numpy as np
import pandas as pd

In [9]:
claims = pd.read_csv('D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 3 - Insurance Claims Case Study\claims.csv')

In [10]:
cust = pd.read_csv('D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 3 - Insurance Claims Case Study\cust_demographics.csv')

In [11]:
claims.head()

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent
0,54004764,21868593,Driver error,11/27/2017,Auto,No,Material only,$2980,1.0,No
1,33985796,75740424,Crime,10/03/2018,Home,Unknown,Material only,$2980,3.0,No
2,53522022,30308357,Other driver error,02/02/2018,Auto,No,Material only,$3369.5,1.0,Yes
3,13015401,47830476,Natural causes,06/17/2018,Auto,No,Material only,$1680,1.0,No
4,22890252,19269962,Crime,01/13/2018,Auto,No,Material only,$2680,1.0,No

In [12]:
cust.head()

    CUST_ID  gender DateOfBirth State       Contact   Segment
0  21868593  Female   12-Jan-79    VT  789-916-8172  Platinum
1  75740424  Female   13-Jan-70    ME  265-543-1264    Silver
2  30308357  Female   11-Mar-84    TN  798-631-4758    Silver
3  47830476  Female   01-May-86    MA  413-187-7945    Silver
4  19269962    Male   13-May-77    NV  956-871-8691      Gold

In [13]:
claims.shape

(1100, 10)

In [14]:
cust.shape

(1085, 6)

In [15]:
claims.columns

Index(['claim_id', 'customer_id', 'incident_cause', 'claim_date', 'claim_area',
       'police_report', 'claim_type', 'claim_amount', 'total_policy_claims',
       'fraudulent'],
      dtype='object')

In [16]:
cust.columns

Index(['CUST_ID', 'gender', 'DateOfBirth', 'State', 'Contact', 'Segment'], dtype='object')

In [20]:
df = pd.merge(claims, cust, left_on='customer_id', right_on = 'CUST_ID', how='inner')

In [21]:
df.head()

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,CUST_ID,gender,DateOfBirth,State,Contact,Segment
0,54004764,21868593,Driver error,11/27/2017,Auto,No,Material only,$2980,1.0,No,21868593,Female,12-Jan-79,VT,789-916-8172,Platinum
1,33985796,75740424,Crime,10/03/2018,Home,Unknown,Material only,$2980,3.0,No,75740424,Female,13-Jan-70,ME,265-543-1264,Silver
2,53522022,30308357,Other driver error,02/02/2018,Auto,No,Material only,$3369.5,1.0,Yes,30308357,Female,11-Mar-84,TN,798-631-4758,Silver
3,13015401,47830476,Natural causes,06/17/2018,Auto,No,Material only,$1680,1.0,No,47830476,Female,01-May-86,MA,413-187-7945,Silver
4,22890252,19269962,Crime,01/13/2018,Auto,No,Material only,$2680,1.0,No,19269962,Male,13-May-77,NV,956-871-8691,Gold

In [22]:
df.shape

(1085, 16)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   claim_id             1085 non-null   int64
 1   customer_id          1085 non-null   int64
 2   incident_cause       1085 non-null   object
 3   claim_date           1085 non-null   object
 4   claim_area           1085 non-null   object
 5   police_report        1085 non-null   object
 6   claim_type           1085 non-null   object
 7   claim_amount         1020 non-null   object
 8   total_policy_claims  1075 non-null   float64
 9   fraudulent           1085 non-null   object
 10  CUST_ID              1085 non-null   int64
 11  gender               1085 non-null   object
 12  DateOfBirth          1085 non-null   object
 13  State                1085 non-null   object
 14  Contact              1085 non-null   object
 15  Segment              1085 non-null   object
dtypes: float64(1), int64(3), object(12)
memory usage: 135.8+ KB