In [62]:
import numpy as np
import pandas as pd
import datetime

In [63]:
claims = pd.read_csv('D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 3 - Insurance Claims Case Study\claims.csv')

In [64]:
cust = pd.read_csv('D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 3 - Insurance Claims Case Study\cust_demographics.csv')

In [65]:
claims.head()

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent
0,54004764,21868593,Driver error,11/27/2017,Auto,No,Material only,$2980,1.0,No
1,33985796,75740424,Crime,10/03/2018,Home,Unknown,Material only,$2980,3.0,No
2,53522022,30308357,Other driver error,02/02/2018,Auto,No,Material only,$3369.5,1.0,Yes
3,13015401,47830476,Natural causes,06/17/2018,Auto,No,Material only,$1680,1.0,No
4,22890252,19269962,Crime,01/13/2018,Auto,No,Material only,$2680,1.0,No

In [66]:
cust.head()

    CUST_ID  gender DateOfBirth State       Contact   Segment
0  21868593  Female   12-Jan-79    VT  789-916-8172  Platinum
1  75740424  Female   13-Jan-70    ME  265-543-1264    Silver
2  30308357  Female   11-Mar-84    TN  798-631-4758    Silver
3  47830476  Female   01-May-86    MA  413-187-7945    Silver
4  19269962    Male   13-May-77    NV  956-871-8691      Gold

In [67]:
claims.shape

(1100, 10)

In [68]:
cust.shape

(1085, 6)

In [69]:
claims.columns

Index(['claim_id', 'customer_id', 'incident_cause', 'claim_date', 'claim_area',
       'police_report', 'claim_type', 'claim_amount', 'total_policy_claims',
       'fraudulent'],
      dtype='object')

In [70]:
cust.columns

Index(['CUST_ID', 'gender', 'DateOfBirth', 'State', 'Contact', 'Segment'], dtype='object')

In [71]:
df = pd.merge(claims, cust, left_on='customer_id', right_on = 'CUST_ID', how='inner')

In [72]:
df.head()

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,CUST_ID,gender,DateOfBirth,State,Contact,Segment
0,54004764,21868593,Driver error,11/27/2017,Auto,No,Material only,$2980,1.0,No,21868593,Female,12-Jan-79,VT,789-916-8172,Platinum
1,33985796,75740424,Crime,10/03/2018,Home,Unknown,Material only,$2980,3.0,No,75740424,Female,13-Jan-70,ME,265-543-1264,Silver
2,53522022,30308357,Other driver error,02/02/2018,Auto,No,Material only,$3369.5,1.0,Yes,30308357,Female,11-Mar-84,TN,798-631-4758,Silver
3,13015401,47830476,Natural causes,06/17/2018,Auto,No,Material only,$1680,1.0,No,47830476,Female,01-May-86,MA,413-187-7945,Silver
4,22890252,19269962,Crime,01/13/2018,Auto,No,Material only,$2680,1.0,No,19269962,Male,13-May-77,NV,956-871-8691,Gold

In [73]:
df.shape

(1085, 16)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   claim_id             1085 non-null   int64
 1   customer_id          1085 non-null   int64
 2   incident_cause       1085 non-null   object
 3   claim_date           1085 non-null   object
 4   claim_area           1085 non-null   object
 5   police_report        1085 non-null   object
 6   claim_type           1085 non-null   object
 7   claim_amount         1020 non-null   object
 8   total_policy_claims  1075 non-null   float64
 9   fraudulent           1085 non-null   object
 10  CUST_ID              1085 non-null   int64
 11  gender               1085 non-null   object
 12  DateOfBirth          1085 non-null   object
 13  State                1085 non-null   object
 14  Contact              1085 non-null   object
 15  Segment              1085 non-null   object
dtypes: float64(1), int64(3), object(12)
memory usage: 135.8+ KB

In [76]:
df.drop(columns= 'CUST_ID', inplace=True)

In [77]:
df

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,gender,DateOfBirth,State,Contact,Segment
0,54004764,21868593,Driver error,11/27/2017,Auto,No,Material only,$2980,1.0,No,Female,12-Jan-79,VT,789-916-8172,Platinum
1,33985796,75740424,Crime,10/03/2018,Home,Unknown,Material only,$2980,3.0,No,Female,13-Jan-70,ME,265-543-1264,Silver
2,53522022,30308357,Other driver error,02/02/2018,Auto,No,Material only,$3369.5,1.0,Yes,Female,11-Mar-84,TN,798-631-4758,Silver
3,13015401,47830476,Natural causes,06/17/2018,Auto,No,Material only,$1680,1.0,No,Female,01-May-86,MA,413-187-7945,Silver
4,22890252,19269962,Crime,01/13/2018,Auto,No,Material only,$2680,1.0,No,Male,13-May-77,NV,956-871-8691,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1080,62020796,79539873,Other driver error,09/06/2018,Auto,Yes,Material only,$1770,1.0,No,Female,15-Mar-81,ND,459-425-4319,Platinum
1081,63269067,42364152,Other causes,05/09/2017,Home,No,Material only,$2800,1.0,No,Female,07-Jul-96,ID,529-462-1635,Silver
1082,22690595,19888166,Other driver error,05/15/2017,Auto,Yes,Injury only,$33080,2.0,No,Male,11-Apr-90,WI,712-651-9613,Gold
1083,12376894,11256802,Other driver error,04/18/2017,Auto,No,Material only,$2840,4.0,No,Female,22-Oct-64,LA,469-345-5617,Silver
1084,63226031,61575264,Natural causes,03/16/2017,Auto,No,Material only,$1490,1.0,No,Male,12-Jul-95,WY,182-385-1392,Gold

In [78]:
df['claim_amount'] = df['claim_amount'].str.replace(r'[\$,]','', regex = True)

In [79]:
df['claim_amount'] = df['claim_amount'].str.strip()

In [80]:
df['claim_amount']

0         2980
1         2980
2       3369.5
3         1680
4         2680
         ...
1080      1770
1081      2800
1082     33080
1083      2840
1084      1490
Name: claim_amount, Length: 1085, dtype: object

In [81]:
df['claim_amount'] = pd.to_numeric(df['claim_amount'], errors='coerce')

In [82]:
df.head()

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,gender,DateOfBirth,State,Contact,Segment
0,54004764,21868593,Driver error,11/27/2017,Auto,No,Material only,2980.0,1.0,No,Female,12-Jan-79,VT,789-916-8172,Platinum
1,33985796,75740424,Crime,10/03/2018,Home,Unknown,Material only,2980.0,3.0,No,Female,13-Jan-70,ME,265-543-1264,Silver
2,53522022,30308357,Other driver error,02/02/2018,Auto,No,Material only,3369.5,1.0,Yes,Female,11-Mar-84,TN,798-631-4758,Silver
3,13015401,47830476,Natural causes,06/17/2018,Auto,No,Material only,1680.0,1.0,No,Female,01-May-86,MA,413-187-7945,Silver
4,22890252,19269962,Crime,01/13/2018,Auto,No,Material only,2680.0,1.0,No,Male,13-May-77,NV,956-871-8691,Gold

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   claim_id             1085 non-null   int64
 1   customer_id          1085 non-null   int64
 2   incident_cause       1085 non-null   object
 3   claim_date           1085 non-null   object
 4   claim_area           1085 non-null   object
 5   police_report        1085 non-null   object
 6   claim_type           1085 non-null   object
 7   claim_amount         1020 non-null   float64
 8   total_policy_claims  1075 non-null   float64
 9   fraudulent           1085 non-null   object
 10  gender               1085 non-null   object
 11  DateOfBirth          1085 non-null   object
 12  State                1085 non-null   object
 13  Contact              1085 non-null   object
 14  Segment              1085 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 127.3+ KB

In [84]:
df['claim_date'] = pd.to_datetime(df['claim_date'], format='%m/%d/%Y')

In [85]:
df['DateOfBirth'] = pd.to_datetime(df['DateOfBirth'],format='%d-%b-%y')

In [86]:
df['DateOfBirth'].head()

0   1979-01-12
1   1970-01-13
2   1984-03-11
3   1986-05-01
4   1977-05-13
Name: DateOfBirth, dtype: datetime64[ns]

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   claim_id             1085 non-null   int64
 1   customer_id          1085 non-null   int64
 2   incident_cause       1085 non-null   object
 3   claim_date           1085 non-null   datetime64[ns]
 4   claim_area           1085 non-null   object
 5   police_report        1085 non-null   object
 6   claim_type           1085 non-null   object
 7   claim_amount         1020 non-null   float64
 8   total_policy_claims  1075 non-null   float64
 9   fraudulent           1085 non-null   object
 10  gender               1085 non-null   object
 11  DateOfBirth          1085 non-null   datetime64[ns]
 12  State                1085 non-null   object
 13  Contact              1085 non-null   object
 14  Segment              1085 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(2), object(9)
memory usage: 127.3+ KB