In [79]:
import numpy as np
import pandas as pd
import datetime

In [80]:
claims = pd.read_csv('D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 3 - Insurance Claims Case Study\claims.csv')

In [81]:
cust = pd.read_csv('D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 3 - Insurance Claims Case Study\cust_demographics.csv')

In [82]:
claims.head()

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent
0,54004764,21868593,Driver error,11/27/2017,Auto,No,Material only,$2980,1.0,No
1,33985796,75740424,Crime,10/03/2018,Home,Unknown,Material only,$2980,3.0,No
2,53522022,30308357,Other driver error,02/02/2018,Auto,No,Material only,$3369.5,1.0,Yes
3,13015401,47830476,Natural causes,06/17/2018,Auto,No,Material only,$1680,1.0,No
4,22890252,19269962,Crime,01/13/2018,Auto,No,Material only,$2680,1.0,No

In [83]:
cust.head()

    CUST_ID  gender DateOfBirth State       Contact   Segment
0  21868593  Female   12-Jan-79    VT  789-916-8172  Platinum
1  75740424  Female   13-Jan-70    ME  265-543-1264    Silver
2  30308357  Female   11-Mar-84    TN  798-631-4758    Silver
3  47830476  Female   01-May-86    MA  413-187-7945    Silver
4  19269962    Male   13-May-77    NV  956-871-8691      Gold

In [84]:
claims.shape

(1100, 10)

In [85]:
cust.shape

(1085, 6)

In [86]:
claims.columns

Index(['claim_id', 'customer_id', 'incident_cause', 'claim_date', 'claim_area',
       'police_report', 'claim_type', 'claim_amount', 'total_policy_claims',
       'fraudulent'],
      dtype='object')

In [87]:
cust.columns

Index(['CUST_ID', 'gender', 'DateOfBirth', 'State', 'Contact', 'Segment'], dtype='object')

In [88]:
df = pd.merge(claims, cust, left_on='customer_id', right_on = 'CUST_ID', how='inner')

In [89]:
df.head()

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,CUST_ID,gender,DateOfBirth,State,Contact,Segment
0,54004764,21868593,Driver error,11/27/2017,Auto,No,Material only,$2980,1.0,No,21868593,Female,12-Jan-79,VT,789-916-8172,Platinum
1,33985796,75740424,Crime,10/03/2018,Home,Unknown,Material only,$2980,3.0,No,75740424,Female,13-Jan-70,ME,265-543-1264,Silver
2,53522022,30308357,Other driver error,02/02/2018,Auto,No,Material only,$3369.5,1.0,Yes,30308357,Female,11-Mar-84,TN,798-631-4758,Silver
3,13015401,47830476,Natural causes,06/17/2018,Auto,No,Material only,$1680,1.0,No,47830476,Female,01-May-86,MA,413-187-7945,Silver
4,22890252,19269962,Crime,01/13/2018,Auto,No,Material only,$2680,1.0,No,19269962,Male,13-May-77,NV,956-871-8691,Gold

In [90]:
df.shape

(1085, 16)

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   claim_id             1085 non-null   int64
 1   customer_id          1085 non-null   int64
 2   incident_cause       1085 non-null   object
 3   claim_date           1085 non-null   object
 4   claim_area           1085 non-null   object
 5   police_report        1085 non-null   object
 6   claim_type           1085 non-null   object
 7   claim_amount         1020 non-null   object
 8   total_policy_claims  1075 non-null   float64
 9   fraudulent           1085 non-null   object
 10  CUST_ID              1085 non-null   int64
 11  gender               1085 non-null   object
 12  DateOfBirth          1085 non-null   object
 13  State                1085 non-null   object
 14  Contact              1085 non-null   object
 15  Segment              1085 non-null   object
dtypes: float64(1), int64(3), object(12)
memory usage: 135.8+ KB

In [92]:
df.drop(columns= 'CUST_ID', inplace=True)

In [93]:
df

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,gender,DateOfBirth,State,Contact,Segment
0,54004764,21868593,Driver error,11/27/2017,Auto,No,Material only,$2980,1.0,No,Female,12-Jan-79,VT,789-916-8172,Platinum
1,33985796,75740424,Crime,10/03/2018,Home,Unknown,Material only,$2980,3.0,No,Female,13-Jan-70,ME,265-543-1264,Silver
2,53522022,30308357,Other driver error,02/02/2018,Auto,No,Material only,$3369.5,1.0,Yes,Female,11-Mar-84,TN,798-631-4758,Silver
3,13015401,47830476,Natural causes,06/17/2018,Auto,No,Material only,$1680,1.0,No,Female,01-May-86,MA,413-187-7945,Silver
4,22890252,19269962,Crime,01/13/2018,Auto,No,Material only,$2680,1.0,No,Male,13-May-77,NV,956-871-8691,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1080,62020796,79539873,Other driver error,09/06/2018,Auto,Yes,Material only,$1770,1.0,No,Female,15-Mar-81,ND,459-425-4319,Platinum
1081,63269067,42364152,Other causes,05/09/2017,Home,No,Material only,$2800,1.0,No,Female,07-Jul-96,ID,529-462-1635,Silver
1082,22690595,19888166,Other driver error,05/15/2017,Auto,Yes,Injury only,$33080,2.0,No,Male,11-Apr-90,WI,712-651-9613,Gold
1083,12376894,11256802,Other driver error,04/18/2017,Auto,No,Material only,$2840,4.0,No,Female,22-Oct-64,LA,469-345-5617,Silver
1084,63226031,61575264,Natural causes,03/16/2017,Auto,No,Material only,$1490,1.0,No,Male,12-Jul-95,WY,182-385-1392,Gold

In [94]:
df['claim_amount'] = df['claim_amount'].str.replace(r'[\$,]','', regex = True)

In [95]:
df['claim_amount'] = df['claim_amount'].str.strip()

In [96]:
df['claim_amount']

0         2980
1         2980
2       3369.5
3         1680
4         2680
         ...
1080      1770
1081      2800
1082     33080
1083      2840
1084      1490
Name: claim_amount, Length: 1085, dtype: object

In [97]:
df['claim_amount'] = pd.to_numeric(df['claim_amount'], errors='coerce')

In [98]:
df.head()

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,gender,DateOfBirth,State,Contact,Segment
0,54004764,21868593,Driver error,11/27/2017,Auto,No,Material only,2980.0,1.0,No,Female,12-Jan-79,VT,789-916-8172,Platinum
1,33985796,75740424,Crime,10/03/2018,Home,Unknown,Material only,2980.0,3.0,No,Female,13-Jan-70,ME,265-543-1264,Silver
2,53522022,30308357,Other driver error,02/02/2018,Auto,No,Material only,3369.5,1.0,Yes,Female,11-Mar-84,TN,798-631-4758,Silver
3,13015401,47830476,Natural causes,06/17/2018,Auto,No,Material only,1680.0,1.0,No,Female,01-May-86,MA,413-187-7945,Silver
4,22890252,19269962,Crime,01/13/2018,Auto,No,Material only,2680.0,1.0,No,Male,13-May-77,NV,956-871-8691,Gold

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   claim_id             1085 non-null   int64
 1   customer_id          1085 non-null   int64
 2   incident_cause       1085 non-null   object
 3   claim_date           1085 non-null   object
 4   claim_area           1085 non-null   object
 5   police_report        1085 non-null   object
 6   claim_type           1085 non-null   object
 7   claim_amount         1020 non-null   float64
 8   total_policy_claims  1075 non-null   float64
 9   fraudulent           1085 non-null   object
 10  gender               1085 non-null   object
 11  DateOfBirth          1085 non-null   object
 12  State                1085 non-null   object
 13  Contact              1085 non-null   object
 14  Segment              1085 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 127.3+ KB

In [100]:
df['claim_date'] = pd.to_datetime(df['claim_date'], format='%m/%d/%Y')

In [101]:
df['DateOfBirth'] = pd.to_datetime(df['DateOfBirth'],format='%d-%b-%y')

In [102]:
df['DateOfBirth'].head()

0   1979-01-12
1   1970-01-13
2   1984-03-11
3   1986-05-01
4   1977-05-13
Name: DateOfBirth, dtype: datetime64[ns]

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   claim_id             1085 non-null   int64
 1   customer_id          1085 non-null   int64
 2   incident_cause       1085 non-null   object
 3   claim_date           1085 non-null   datetime64[ns]
 4   claim_area           1085 non-null   object
 5   police_report        1085 non-null   object
 6   claim_type           1085 non-null   object
 7   claim_amount         1020 non-null   float64
 8   total_policy_claims  1075 non-null   float64
 9   fraudulent           1085 non-null   object
 10  gender               1085 non-null   object
 11  DateOfBirth          1085 non-null   datetime64[ns]
 12  State                1085 non-null   object
 13  Contact              1085 non-null   object
 14  Segment              1085 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(2), object(9)
memory usage: 127.3+ KB

In [104]:
df.head()

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,gender,DateOfBirth,State,Contact,Segment
0,54004764,21868593,Driver error,2017-11-27,Auto,No,Material only,2980.0,1.0,No,Female,1979-01-12,VT,789-916-8172,Platinum
1,33985796,75740424,Crime,2018-10-03,Home,Unknown,Material only,2980.0,3.0,No,Female,1970-01-13,ME,265-543-1264,Silver
2,53522022,30308357,Other driver error,2018-02-02,Auto,No,Material only,3369.5,1.0,Yes,Female,1984-03-11,TN,798-631-4758,Silver
3,13015401,47830476,Natural causes,2018-06-17,Auto,No,Material only,1680.0,1.0,No,Female,1986-05-01,MA,413-187-7945,Silver
4,22890252,19269962,Crime,2018-01-13,Auto,No,Material only,2680.0,1.0,No,Male,1977-05-13,NV,956-871-8691,Gold

In [105]:
df['claim_type'].value_counts()

claim_type
Material only          653
Material and injury    237
Injury only            195
Name: count, dtype: int64

In [106]:
df['police_report'].value_counts()

police_report
No         621
Unknown    296
Yes        168
Name: count, dtype: int64

In [107]:
df['Alert_flag'] = ((df['claim_type'] == 'Injury only') & (df['police_report'] == 'No')).astype(int)

In [108]:
df

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,gender,DateOfBirth,State,Contact,Segment,Alert_flag
0,54004764,21868593,Driver error,2017-11-27,Auto,No,Material only,2980.0,1.0,No,Female,1979-01-12,VT,789-916-8172,Platinum,0
1,33985796,75740424,Crime,2018-10-03,Home,Unknown,Material only,2980.0,3.0,No,Female,1970-01-13,ME,265-543-1264,Silver,0
2,53522022,30308357,Other driver error,2018-02-02,Auto,No,Material only,3369.5,1.0,Yes,Female,1984-03-11,TN,798-631-4758,Silver,0
3,13015401,47830476,Natural causes,2018-06-17,Auto,No,Material only,1680.0,1.0,No,Female,1986-05-01,MA,413-187-7945,Silver,0
4,22890252,19269962,Crime,2018-01-13,Auto,No,Material only,2680.0,1.0,No,Male,1977-05-13,NV,956-871-8691,Gold,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1080,62020796,79539873,Other driver error,2018-09-06,Auto,Yes,Material only,1770.0,1.0,No,Female,1981-03-15,ND,459-425-4319,Platinum,0
1081,63269067,42364152,Other causes,2017-05-09,Home,No,Material only,2800.0,1.0,No,Female,1996-07-07,ID,529-462-1635,Silver,0
1082,22690595,19888166,Other driver error,2017-05-15,Auto,Yes,Injury only,33080.0,2.0,No,Male,1990-04-11,WI,712-651-9613,Gold,0
1083,12376894,11256802,Other driver error,2017-04-18,Auto,No,Material only,2840.0,4.0,No,Female,2064-10-22,LA,469-345-5617,Silver,0
1084,63226031,61575264,Natural causes,2017-03-16,Auto,No,Material only,1490.0,1.0,No,Male,1995-07-12,WY,182-385-1392,Gold,0

In [109]:
df['Alert_flag'].value_counts()

Alert_flag
0    1025
1      60
Name: count, dtype: int64

In [110]:
df[['claim_type', 'police_report', 'Alert_flag']].head()

      claim_type police_report  Alert_flag
0  Material only            No           0
1  Material only       Unknown           0
2  Material only            No           0
3  Material only            No           0
4  Material only            No           0

In [111]:
df[df['Alert_flag'] == 1].shape

(60, 16)

In [112]:
df = df.sort_values(by= 'claim_date', ascending= False)

In [113]:
df = df.drop_duplicates(subset='customer_id', keep= 'first')

In [114]:
df

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,gender,DateOfBirth,State,Contact,Segment,Alert_flag
751,25213498,28932340,Driver error,2018-10-30,Auto,Unknown,Material only,NaN,1.0,No,Male,1996-01-05,LA,652-265-8231,Gold,0
1077,91386759,65208809,Natural causes,2018-10-30,Auto,No,Material only,2290.0,1.0,No,Male,2064-04-22,VA,286-128-6132,Platinum,0
222,49735712,17682060,Crime,2018-10-30,Home,Unknown,Material and injury,17020.0,1.0,No,Female,1974-11-21,NV,186-195-3465,Gold,0
234,52377605,40480522,Driver error,2018-10-30,Auto,Unknown,Material and injury,26310.0,1.0,No,Female,1984-05-30,NV,739-259-6835,Gold,0
282,99775483,93915431,Other causes,2018-10-30,Auto,No,Material and injury,42124.5,1.0,Yes,Male,2067-09-08,ME,134-785-1687,Gold,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,58878919,29323970,Driver error,2017-01-01,Auto,Unknown,Material only,1840.0,1.0,Yes,Male,1971-03-03,NE,783-653-9163,Gold,0
308,9476314,65176092,Other causes,2017-01-01,Auto,No,Material and injury,37290.0,3.0,No,Male,1975-11-23,NC,651-379-2486,Silver,0
905,42280334,42664554,Other causes,2017-01-01,Auto,No,Injury only,27670.0,1.0,No,Female,1993-08-13,TN,396-973-2531,Gold,1
191,23636125,64840478,Other driver error,2017-01-01,Auto,Unknown,Material and injury,17290.0,1.0,No,Female,1974-02-14,NM,918-174-7461,Silver,0
173,25647821,74155265,Natural causes,2017-01-01,Auto,No,Material only,2080.0,1.0,No,Male,1985-11-16,TX,392-739-4873,Gold,0

In [115]:
df.isnull().sum()

claim_id                0
customer_id             0
incident_cause          0
claim_date              0
claim_area              0
police_report           0
claim_type              0
claim_amount           65
total_policy_claims    10
fraudulent              0
gender                  0
DateOfBirth             0
State                   0
Contact                 0
Segment                 0
Alert_flag              0
dtype: int64

In [116]:
df.dtypes

claim_id                        int64
customer_id                     int64
incident_cause                 object
claim_date             datetime64[ns]
claim_area                     object
police_report                  object
claim_type                     object
claim_amount                  float64
total_policy_claims           float64
fraudulent                     object
gender                         object
DateOfBirth            datetime64[ns]
State                          object
Contact                        object
Segment                        object
Alert_flag                      int64
dtype: object

In [117]:
# handling missing values
num_cols = df.select_dtypes(include= ['int64', 'float64']).columns

In [118]:
num_cols

Index(['claim_id', 'customer_id', 'claim_amount', 'total_policy_claims',
       'Alert_flag'],
      dtype='object')

In [119]:
for col in num_cols:
    df[col] = df[col].fillna(df[col].mean())

In [120]:
df

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,gender,DateOfBirth,State,Contact,Segment,Alert_flag
751,25213498,28932340,Driver error,2018-10-30,Auto,Unknown,Material only,12501.726555,1.0,No,Male,1996-01-05,LA,652-265-8231,Gold,0
1077,91386759,65208809,Natural causes,2018-10-30,Auto,No,Material only,2290.000000,1.0,No,Male,2064-04-22,VA,286-128-6132,Platinum,0
222,49735712,17682060,Crime,2018-10-30,Home,Unknown,Material and injury,17020.000000,1.0,No,Female,1974-11-21,NV,186-195-3465,Gold,0
234,52377605,40480522,Driver error,2018-10-30,Auto,Unknown,Material and injury,26310.000000,1.0,No,Female,1984-05-30,NV,739-259-6835,Gold,0
282,99775483,93915431,Other causes,2018-10-30,Auto,No,Material and injury,42124.500000,1.0,Yes,Male,2067-09-08,ME,134-785-1687,Gold,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,58878919,29323970,Driver error,2017-01-01,Auto,Unknown,Material only,1840.000000,1.0,Yes,Male,1971-03-03,NE,783-653-9163,Gold,0
308,9476314,65176092,Other causes,2017-01-01,Auto,No,Material and injury,37290.000000,3.0,No,Male,1975-11-23,NC,651-379-2486,Silver,0
905,42280334,42664554,Other causes,2017-01-01,Auto,No,Injury only,27670.000000,1.0,No,Female,1993-08-13,TN,396-973-2531,Gold,1
191,23636125,64840478,Other driver error,2017-01-01,Auto,Unknown,Material and injury,17290.000000,1.0,No,Female,1974-02-14,NM,918-174-7461,Silver,0
173,25647821,74155265,Natural causes,2017-01-01,Auto,No,Material only,2080.000000,1.0,No,Male,1985-11-16,TX,392-739-4873,Gold,0

In [121]:
df.isnull().sum()

claim_id               0
customer_id            0
incident_cause         0
claim_date             0
claim_area             0
police_report          0
claim_type             0
claim_amount           0
total_policy_claims    0
fraudulent             0
gender                 0
DateOfBirth            0
State                  0
Contact                0
Segment                0
Alert_flag             0
dtype: int64

In [122]:
# Categorizing the age groups

In [123]:
df

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,gender,DateOfBirth,State,Contact,Segment,Alert_flag
751,25213498,28932340,Driver error,2018-10-30,Auto,Unknown,Material only,12501.726555,1.0,No,Male,1996-01-05,LA,652-265-8231,Gold,0
1077,91386759,65208809,Natural causes,2018-10-30,Auto,No,Material only,2290.000000,1.0,No,Male,2064-04-22,VA,286-128-6132,Platinum,0
222,49735712,17682060,Crime,2018-10-30,Home,Unknown,Material and injury,17020.000000,1.0,No,Female,1974-11-21,NV,186-195-3465,Gold,0
234,52377605,40480522,Driver error,2018-10-30,Auto,Unknown,Material and injury,26310.000000,1.0,No,Female,1984-05-30,NV,739-259-6835,Gold,0
282,99775483,93915431,Other causes,2018-10-30,Auto,No,Material and injury,42124.500000,1.0,Yes,Male,2067-09-08,ME,134-785-1687,Gold,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,58878919,29323970,Driver error,2017-01-01,Auto,Unknown,Material only,1840.000000,1.0,Yes,Male,1971-03-03,NE,783-653-9163,Gold,0
308,9476314,65176092,Other causes,2017-01-01,Auto,No,Material and injury,37290.000000,3.0,No,Male,1975-11-23,NC,651-379-2486,Silver,0
905,42280334,42664554,Other causes,2017-01-01,Auto,No,Injury only,27670.000000,1.0,No,Female,1993-08-13,TN,396-973-2531,Gold,1
191,23636125,64840478,Other driver error,2017-01-01,Auto,Unknown,Material and injury,17290.000000,1.0,No,Female,1974-02-14,NM,918-174-7461,Silver,0
173,25647821,74155265,Natural causes,2017-01-01,Auto,No,Material only,2080.000000,1.0,No,Male,1985-11-16,TX,392-739-4873,Gold,0

In [124]:
df[df['DateOfBirth'] > pd.Timestamp.today()]

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,gender,DateOfBirth,State,Contact,Segment,Alert_flag
1077,91386759,65208809,Natural causes,2018-10-30,Auto,No,Material only,2290.0,1.0,No,Male,2064-04-22,VA,286-128-6132,Platinum,0
282,99775483,93915431,Other causes,2018-10-30,Auto,No,Material and injury,42124.5,1.0,Yes,Male,2067-09-08,ME,134-785-1687,Gold,0
1055,43042986,58451506,Natural causes,2018-10-30,Auto,No,Material only,2420.0,1.0,No,Male,2068-04-22,FL,673-574-7823,Gold,0
977,9261301,53042145,Other causes,2018-10-23,Auto,Unknown,Material only,2553.0,4.0,Yes,Female,2064-10-04,TN,139-746-7128,Platinum,0
728,26678377,28590552,Other causes,2018-10-23,Auto,Unknown,Material and injury,25160.0,1.0,No,Female,2064-01-10,TN,189-813-7561,Silver,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,30422665,70088729,Driver error,2017-01-07,Home,No,Material only,1552.5,1.0,Yes,Male,2062-12-06,WI,453-475-2863,Silver,0
840,58440592,18426154,Other causes,2017-01-07,Auto,Yes,Material and injury,21590.0,1.0,No,Male,2060-06-07,NJ,879-485-1945,Gold,0
955,85590604,41128407,Other causes,2017-01-07,Auto,No,Injury only,36670.0,2.0,No,Male,2066-07-09,SD,812-324-7932,Silver,1
291,11682102,24579061,Natural causes,2017-01-07,Auto,No,Material only,1770.0,1.0,No,Female,2067-11-24,IN,763-365-2837,Platinum,0
116,39131766,39587790,Other causes,2017-01-01,Auto,No,Material only,2967.0,1.0,Yes,Male,2065-01-10,LA,615-154-3516,Gold,0

In [125]:
df.loc[df['DateOfBirth'] > pd.Timestamp.today(), 'DateOfBirth'] -= pd.DateOffset(years=100)

In [126]:
df[df['DateOfBirth'] > pd.Timestamp.today()]

Empty DataFrame
Columns: [claim_id, customer_id, incident_cause, claim_date, claim_area, police_report, claim_type, claim_amount, total_policy_claims, fraudulent, gender, DateOfBirth, State, Contact, Segment, Alert_flag]
Index: []

In [128]:
df['Age'] = (pd.Timestamp.today() - df['DateOfBirth']).dt.days // 365

In [129]:
df

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,gender,DateOfBirth,State,Contact,Segment,Alert_flag,Age
751,25213498,28932340,Driver error,2018-10-30,Auto,Unknown,Material only,12501.726555,1.0,No,Male,1996-01-05,LA,652-265-8231,Gold,0,30
1077,91386759,65208809,Natural causes,2018-10-30,Auto,No,Material only,2290.000000,1.0,No,Male,1964-04-22,VA,286-128-6132,Platinum,0,62
222,49735712,17682060,Crime,2018-10-30,Home,Unknown,Material and injury,17020.000000,1.0,No,Female,1974-11-21,NV,186-195-3465,Gold,0,51
234,52377605,40480522,Driver error,2018-10-30,Auto,Unknown,Material and injury,26310.000000,1.0,No,Female,1984-05-30,NV,739-259-6835,Gold,0,41
282,99775483,93915431,Other causes,2018-10-30,Auto,No,Material and injury,42124.500000,1.0,Yes,Male,1967-09-08,ME,134-785-1687,Gold,0,58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,58878919,29323970,Driver error,2017-01-01,Auto,Unknown,Material only,1840.000000,1.0,Yes,Male,1971-03-03,NE,783-653-9163,Gold,0,55
308,9476314,65176092,Other causes,2017-01-01,Auto,No,Material and injury,37290.000000,3.0,No,Male,1975-11-23,NC,651-379-2486,Silver,0,50
905,42280334,42664554,Other causes,2017-01-01,Auto,No,Injury only,27670.000000,1.0,No,Female,1993-08-13,TN,396-973-2531,Gold,1,32
191,23636125,64840478,Other driver error,2017-01-01,Auto,Unknown,Material and injury,17290.000000,1.0,No,Female,1974-02-14,NM,918-174-7461,Silver,0,52
173,25647821,74155265,Natural causes,2017-01-01,Auto,No,Material only,2080.000000,1.0,No,Male,1985-11-16,TX,392-739-4873,Gold,0,40

In [130]:
df[df['Age'] < 0]

Empty DataFrame
Columns: [claim_id, customer_id, incident_cause, claim_date, claim_area, police_report, claim_type, claim_amount, total_policy_claims, fraudulent, gender, DateOfBirth, State, Contact, Segment, Alert_flag, Age]
Index: []

In [131]:
df['Age_Group'] = pd.cut(
    df['Age'],
    bins=[0, 18, 30, 60, 100],
    labels=['Children', 'Youth', 'Adult', 'Senior'],
    right=False
)

In [132]:
df

,claim_id,customer_id,incident_cause,claim_date,claim_area,police_report,claim_type,claim_amount,total_policy_claims,fraudulent,gender,DateOfBirth,State,Contact,Segment,Alert_flag,Age,Age_Group
751,25213498,28932340,Driver error,2018-10-30,Auto,Unknown,Material only,12501.726555,1.0,No,Male,1996-01-05,LA,652-265-8231,Gold,0,30,Adult
1077,91386759,65208809,Natural causes,2018-10-30,Auto,No,Material only,2290.000000,1.0,No,Male,1964-04-22,VA,286-128-6132,Platinum,0,62,Senior
222,49735712,17682060,Crime,2018-10-30,Home,Unknown,Material and injury,17020.000000,1.0,No,Female,1974-11-21,NV,186-195-3465,Gold,0,51,Adult
234,52377605,40480522,Driver error,2018-10-30,Auto,Unknown,Material and injury,26310.000000,1.0,No,Female,1984-05-30,NV,739-259-6835,Gold,0,41,Adult
282,99775483,93915431,Other causes,2018-10-30,Auto,No,Material and injury,42124.500000,1.0,Yes,Male,1967-09-08,ME,134-785-1687,Gold,0,58,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,58878919,29323970,Driver error,2017-01-01,Auto,Unknown,Material only,1840.000000,1.0,Yes,Male,1971-03-03,NE,783-653-9163,Gold,0,55,Adult
308,9476314,65176092,Other causes,2017-01-01,Auto,No,Material and injury,37290.000000,3.0,No,Male,1975-11-23,NC,651-379-2486,Silver,0,50,Adult
905,42280334,42664554,Other causes,2017-01-01,Auto,No,Injury only,27670.000000,1.0,No,Female,1993-08-13,TN,396-973-2531,Gold,1,32,Adult
191,23636125,64840478,Other driver error,2017-01-01,Auto,Unknown,Material and injury,17290.000000,1.0,No,Female,1974-02-14,NM,918-174-7461,Silver,0,52,Adult
173,25647821,74155265,Natural causes,2017-01-01,Auto,No,Material only,2080.000000,1.0,No,Male,1985-11-16,TX,392-739-4873,Gold,0,40,Adult